name = "Simply One Block"
author = "cassiancc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1e0b168fe7235b5f7ac61dd901c370163648413bf5e0a8d6dfbf417335728a6"

[versions]
fabric = "0.15.7"
minecraft = "22w13oneblockatatime"

[options]
acceptable-game-versions = ["1.18.2"]
